"""Pydantic models for API requests and responses."""
from pydantic import BaseModel, Field


class VideoBrief(BaseModel):
    """Structured video brief generated by AI."""

    hook: str = Field(..., description="Opening hook to grab viewer attention")
    body_points: list[str] = Field(
        ...,
        min_length=3,
        max_length=3,
        description="Three main body points for the video",
    )
    cta: str = Field(..., description="Call-to-action to end the video")
    visual_suggestions: list[str] = Field(
        ...,
        description="Visual suggestions for each section",
    )


class TrendContentResponse(BaseModel):
    """Response model for /generate-trend-content endpoint."""

    region: str = Field(..., description="Region used for trends (US or Israel)")
    trends: list[str] = Field(..., description="Top 5 daily trending searches")
    predicted_sub_trend: str = Field(
        ...,
        description="AI-predicted sub-trend that will peak in ~7 days",
    )
    video_brief: VideoBrief = Field(
        ...,
        description="Structured video script/storyboard brief",
    )
